### ISSUE TITLE
Some orders not being recognised when given

### ISSUE THREAD

**Issue by JamblaInc** [MMagicala/gnome-restaurant#1]
The choc saturday is referred to as 'chocolate saturday' when the order is given to the player. The blurberry special is referred to as 'Blurberry special' when the order is given to the player. 

When you define the itemOrders map, the key is what is used to search for the item order when given to the player. Therefore I believe you need to change 'choc saturday' to 'chocolate saturday' and 'blurberry special' to 'Blurberry special'.

**Comment by MMagicala** [comment]
Okay, I'll look into that

**Comment by MMagicala** [comment]
Its pretty difficult to test this in-game because of the sheer number of orders possible. Could you recommend a way to get the right strings so I can correct them in my code?

**Comment by JamblaInc** [comment]
Here you go:
![Blub spec](https://user-images.githubusercontent.com/40252392/98236052-a3c44a00-1f5a-11eb-9aea-469e408b15b4.PNG)
![choc saturday](https://user-images.githubusercontent.com/40252392/98236067-a757d100-1f5a-11eb-9cc6-ff58d504d110.PNG)

**Comment by MMagicala** [comment]
Doesn't Runelite have a way to dump in game text?

**Comment by JamblaInc** [comment]
I'm not sure mate, haven't come across it when I was working on Runelite

**Comment by MarbleTurtle** [comment]
Current implantation is case sensitive causing it to miss the Blurberry special while chocolate saturday is simply misspelled (due to not matching the item itself), the wiki discord may have a proper list of transcripts between the npc for request

**Comment by MMagicala** [comment]
Issue fixed
https://github.com/MMagicala/gnome-restaurant/commit/c3d5fbffae44543337ba0bb04b49fe7e288e85d6
