### ISSUE TITLE
Viewing Aluft aloft box does not update assignment

### ISSUE THREAD

**Issue by Nightfirecat** [MMagicala/gnome-restaurant#5]
Similar to #4, viewing your Aluft aloft box does not cause the plugin to update the active delivery assignment.

**Comment by MMagicala** [comment]
Could you elaborate on this? I'm not sure what you mean.

**Comment by Nightfirecat** [comment]
If you have an [Aluft aloft box](https://oldschool.runescape.wiki/w/Aluft_aloft_box) in your inventory, you're able to `Check` it to see information about your current delivery. (target, time, and recipe) Given that #4 was fixed, this is a pretty niche addition imo since it's basically only useful if you accidentally get a delivery assignment without a chat dialog appearing. (ie. press spacebar and click to walk away in the same tick before the chat dialog would have appeared)
